In [3]:
from empiricaldist import Pmf

In [2]:
!pip install empiricaldist


  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for empiricaldist: filename=empiricaldist-0.7.5-py3-none-any.whl size=12482 sha256=77fc4cc05a08b5703a037a6701e7c46d826141e82e5b297dd9e3b78f365dbe31
  Stored in directory: c:\users\david\appdata\local\pip\cache\wheels\50\76\80\cd870fa069549e0ac217149202c957ab5a175bea03a287d358
Successfully built empiricaldist


In [4]:
coin = Pmf()
coin['heads'] = 1/2
coin['tails'] = 1/2
coin

heads    0.5
tails    0.5
dtype: float64

In [5]:
die = Pmf.from_seq([1,2,3,4,5,6])
die

1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: , dtype: float64

In [6]:
letters = Pmf.from_seq(list('Mississippi'))
letters

M    0.090909
i    0.363636
p    0.181818
s    0.363636
Name: , dtype: float64

In [7]:
letters['s']

0.36363636363636365

In [8]:
try:
    letters['t']
except KeyError as e:
    print(type(e))

<class 'KeyError'>


In [9]:
letters('s')

0.36363636363636365

In [10]:
letters('t')

0

In [11]:
die([1,4,7])

array([0.16666667, 0.16666667, 0.        ])

In [6]:
array([0.16666667, 0.16666667, 0.        ])

NameError: name 'array' is not defined

In [18]:
import numpy as np


In [14]:
np.array([0.16666667, 0.16666667, 0.])


array([0.16666667, 0.16666667, 0.        ])

In [19]:
!pip install numpy


In [20]:
import numpy as np


In [21]:
my_array = np.array([0.16666667, 0.16666667, 0.])


In [22]:
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])
prior

Bowl 1    0.5
Bowl 2    0.5
Name: , dtype: float64

In [24]:
likelihood_vanilla = [0.75, 0.5]
posterior = prior * likelihood_vanilla
posterior

Bowl 1    0.375
Bowl 2    0.250
Name: , dtype: float64

In [25]:
posterior.normalize()

0.625

In [26]:
posterior

Bowl 1    0.6
Bowl 2    0.4
Name: , dtype: float64

In [27]:
posterior('Bowl 1')

0.6

In [28]:
posterior *= likelihood_vanilla
posterior.normalize()
posterior

Bowl 1    0.692308
Bowl 2    0.307692
Name: , dtype: float64

In [29]:
likelihood_chocolate = [0.25, 0.5]

In [30]:
posterior *= likelihood_chocolate
posterior.normalize()
posterior

Bowl 1    0.529412
Bowl 2    0.470588
Name: , dtype: float64

In [31]:
import numpy as np

hypos = np.arange(101)

In [32]:
prior = Pmf(1, hypos)
prior.normalize()

101

In [33]:
prior.head()

0    0.009901
1    0.009901
2    0.009901
dtype: float64

In [34]:
likelihood_vanilla = hypos/100
likelihood_vanilla[:5]

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [35]:
posterior1 = prior * likelihood_vanilla
posterior1.normalize()
posterior1.head()

0    0.000000
1    0.000198
2    0.000396
dtype: float64

In [4]:
from utils import decorate

def decorate_bowls(title):
    decorate(xlabel='Bowl #',
             ylabel='PMF',
             title=title)

In [39]:
!pip install statsmodels


   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB 330.3 kB/s eta 0:00:30
   ---------------------------------------- 0.0/9.8 MB 330.3 kB/s eta 0:00:30
   ---------------------------------------- 0.1/9.8 MB 365.7 kB/s eta 0:00:27
    --------------------------------------- 0.1/9.8 MB 554.9 kB/s eta 0:00:18
   - -------------------------------------- 0.3/9.8 MB 1.4 MB/s eta 0:00:08
   -- ------------------------------------- 0.6/9.8 MB 2.0 MB/s eta 0:00:05
   --- ------------------------------------ 0.9/9.8 MB 2.7 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/9.8 MB 3.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.7/9.8 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.8 MB 4.3 MB/s eta 0:00:02
   ---------- -----------

In [41]:
!pip install seaborn


   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/294.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/294.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/294.9 kB 262.6 kB/s eta 0:00:02
   ----- --------------------------------- 41.0/294.9 kB 245.8 kB/s eta 0:00:02
   --------- ----------------------------- 71.7/294.9 kB 328.6 kB/s eta 0:00:01
   --------------- ---------------------- 122.9/294.9 kB 481.4 kB/s eta 0:00:01
   ---------------------------------------- 294.9/294.9 kB 1.0 MB/s eta 0:00:00


In [ ]:
prior.plot(label='prior', color='C5')
posterior1.plot(label='posterior', color='C4')
decorate_bowls('Posterior after one vanilla cookie')

In [ ]:
# Example using a uniform prior with bowls
import numpy as np
import pandas as pd
from empiricaldist import Pmf

# Define the prior distribution
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Plot the prior distribution
prior.plot(label='prior', color='C5')


In [2]:
from utils import decorate

def decorate_bowls(title):
    decorate(xlabel='Bowl #',
             ylabel='PMF',
             title=title)

In [ ]:
prior.plot(label='prior', color='C5')
posterior1.plot(label='posterior', color='C4')
decorate_bowls('Posterior after one vanilla cookie')

In [ ]:
posterior2 = posterior1 * likelihood_vanilla
posterior2.normalize()

In [1]:
posterior3.idxmax()

NameError: name 'posterior3' is not defined

In [ ]:
prior = Pmf(1, hypos)
prior.normalize()

In [2]:
import numpy as np

hypos = np.arange(101)

In [2]:
from empiricaldist import Pmf

# Example prior distribution for two bowls
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])


In [3]:
# Assume we have likelihoods based on observing vanilla cookies
likelihood_vanilla = {
    'Bowl 1': 0.75,  # 75% chance of vanilla from Bowl 1
    'Bowl 2': 0.5    # 50% chance of vanilla from Bowl 2
}

# Update the prior with one observation of vanilla cookie
posterior1 = prior.copy()
posterior1 *= likelihood_vanilla
posterior1.normalize()

# Assume we have further observations and updates
# Update the posterior with another vanilla cookie
posterior2 = posterior1.copy()
posterior2 *= likelihood_vanilla
posterior2.normalize()

# Update again for the third vanilla cookie
posterior3 = posterior2.copy()
posterior3 *= likelihood_vanilla
posterior3.normalize()


TypeError: unsupported operand type(s) for *: 'float' and 'dict'

In [4]:
# Iterate over each hypothesis in the prior (Bowl 1 and Bowl 2)
for hypo in prior:
    # Multiply the prior probability of each hypothesis by the likelihood of observing the data
    prior[hypo] *= likelihood_vanilla[hypo]

# Normalize the posterior to ensure the probabilities sum to 1
prior.normalize()

# Assign the posterior to posterior1 (after the first observation)
posterior1 = prior.copy()
posterior1


KeyError: 0.5

In [5]:
from empiricaldist import Pmf

# Prior distribution for two bowls
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Likelihood of observing a vanilla cookie from each bowl
likelihood_vanilla = {
    'Bowl 1': 0.75,  # 75% chance of vanilla from Bowl 1
    'Bowl 2': 0.5    # 50% chance of vanilla from Bowl 2
}

# Update the prior based on the likelihood of observing one vanilla cookie
for hypo in prior:
    prior[hypo] *= likelihood_vanilla[hypo]

# Normalize to get the posterior
prior.normalize()

# Posterior after one observation of a vanilla cookie
posterior1 = prior.copy()
print(posterior1)


KeyError: 0.5

In [7]:
posterior *= likelihood_chocolate
posterior.normalize()
posterior

NameError: name 'posterior' is not defined

In [8]:
from empiricaldist import Pmf

In [9]:
coin = Pmf()
coin['heads'] = 1/2
coin['tails'] = 1/2
coin

heads    0.5
tails    0.5
dtype: float64

In [10]:
die = Pmf.from_seq([1,2,3,4,5,6])
die

1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: , dtype: float64

In [11]:
letters = Pmf.from_seq(list('Mississippi'))
letters

M    0.090909
i    0.363636
p    0.181818
s    0.363636
Name: , dtype: float64

In [12]:
letters['s']

0.36363636363636365

In [13]:
letters('s')

0.36363636363636365

In [14]:
letters('t')

0

In [15]:
die([1,4,7])

array([0.16666667, 0.16666667, 0.        ])

In [16]:
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])
prior

Bowl 1    0.5
Bowl 2    0.5
Name: , dtype: float64

In [17]:
likelihood_vanilla = [0.75, 0.5]
posterior = prior * likelihood_vanilla
posterior

Bowl 1    0.375
Bowl 2    0.250
Name: , dtype: float64

In [18]:
posterior.normalize()

0.625

In [19]:
posterior

Bowl 1    0.6
Bowl 2    0.4
Name: , dtype: float64

In [20]:
posterior('Bowl 1')

0.6

In [21]:
posterior *= likelihood_vanilla
posterior.normalize()
posterior

Bowl 1    0.692308
Bowl 2    0.307692
Name: , dtype: float64

In [22]:
likelihood_chocolate = [0.25, 0.5]

In [23]:
posterior *= likelihood_chocolate
posterior.normalize()
posterior

Bowl 1    0.529412
Bowl 2    0.470588
Name: , dtype: float64

In [24]:
import numpy as np

hypos = np.arange(101)

In [25]:
prior = Pmf(1, hypos)
prior.normalize()

101

In [26]:
prior.head()

0    0.009901
1    0.009901
2    0.009901
dtype: float64

In [27]:
likelihood_vanilla = hypos/100
likelihood_vanilla[:5]

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [28]:
posterior1 = prior * likelihood_vanilla
posterior1.normalize()
posterior1.head()

0    0.000000
1    0.000198
2    0.000396
dtype: float64

In [29]:
from utils import decorate

def decorate_bowls(title):
    decorate(xlabel='Bowl #',
             ylabel='PMF',
             title=title)

In [ ]:
prior.plot(label='prior', color='C5')
posterior1.plot(label='posterior', color='C4')
decorate_bowls('Posterior after one vanilla cookie')

In [ ]:
posterior2 = posterior1 * likelihood_vanilla
posterior2.normalize()

In [1]:
0.6699999999999999

0.6699999999999999

In [19]:
from empiricaldist import Pmf
import numpy as np

# Step 1: Define the prior
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Step 2: Define the likelihood for vanilla cookies
likelihood_vanilla = {
    'Bowl 1': 0.75,
    'Bowl 2': 0.5
}

# Update the prior for vanilla cookie to get posterior1
for hypo in prior:
    prior[hypo] *= likelihood_vanilla[hypo]
prior.normalize()
posterior1 = prior.copy()

# Step 3: Define the likelihood for chocolate cookies
likelihood_chocolate = {
    'Bowl 1': 0.5,
    'Bowl 2': 0.25
}

# Update posterior1 for chocolate cookie to get posterior2
for hypo in posterior1:
    posterior1[hypo] *= likelihood_chocolate[hypo]
posterior1.normalize()
posterior2 = posterior1.copy()

# Step 4: Update again (if needed) based on third observation or additional likelihoods
# Define likelihoods for third observation
# Assuming you want to use `hypos` here:
hypos = np.array([50, 100])  # Example numeric hypotheses

# Calculate likelihood for chocolate cookies based on `hypos`
likelihood_chocolate = 1 - hypos / 100

# Apply the likelihood to posterior2 to get posterior3
for i, hypo in enumerate(posterior2):
    posterior2[hypo] *= likelihood_chocolate[i]

posterior2.normalize()

# Posterior after third update
posterior3 = posterior2.copy()
print(posterior3)


KeyError: 0.5

In [3]:
posterior3.idxmax()

NameError: name 'posterior3' is not defined

In [4]:
posterior3.idxmax()


NameError: name 'posterior3' is not defined

In [5]:
import numpy as np
from empiricaldist import Pmf

# Define the prior distribution for two bowls
hypos = np.array([50, 100])  # Hypothetical percentages for two bowls

# Define likelihood for chocolate cookies
likelihood_chocolate = 1 - hypos / 100

# Define a simple prior (equal probability for both hypotheses)
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Update the prior using the likelihood of observing a chocolate cookie
for i, hypo in enumerate(prior):
    prior[hypo] *= likelihood_chocolate[i]

# Normalize the posterior
prior.normalize()

# Posterior after one observation of a chocolate cookie
posterior3 = prior.copy()
print(posterior3)


KeyError: 0.5

In [8]:
from empiricaldist import Pmf

# Define the prior distribution with proper labels
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Define the likelihood for chocolate cookies based on each bowl
# Ensure the order matches the keys in `prior`
likelihood_chocolate = {
    'Bowl 1': 0.5,  # Likelihood of chocolate from Bowl 1
    'Bowl 2': 0.25  # Likelihood of chocolate from Bowl 2
}

# Update the prior using the likelihood of observing a chocolate cookie
for hypo in prior:
    prior[hypo] *= likelihood_chocolate[hypo]

# Normalize to get the posterior
prior.normalize()

# Posterior after one observation of a chocolate cookie
posterior3 = prior.copy()
print(posterior3)


KeyError: 0.5

In [10]:
from empiricaldist import Pmf

# Define the prior distribution for two bowls
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Define likelihood for vanilla cookies
likelihood_vanilla = {
    'Bowl 1': 0.75,  # Likelihood of vanilla from Bowl 1
    'Bowl 2': 0.5    # Likelihood of vanilla from Bowl 2
}

# Update the prior based on the likelihood of observing one vanilla cookie
for hypo in prior:
    prior[hypo] *= likelihood_vanilla[hypo]

# Normalize the posterior
prior.normalize()

# Posterior after one vanilla cookie
posterior1 = prior.copy()


KeyError: 0.5

In [11]:
from empiricaldist import Pmf

# Define the prior distribution for two bowls
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Define likelihood for vanilla cookies
likelihood_vanilla = {
    'Bowl 1': 0.75,  # Likelihood of vanilla from Bowl 1
    'Bowl 2': 0.5    # Likelihood of vanilla from Bowl 2
}

# Update the prior based on the likelihood of observing one vanilla cookie
for hypo in prior:
    prior[hypo] *= likelihood_vanilla[hypo]

# Normalize the posterior
prior.normalize()

# Posterior after one vanilla cookie
posterior1 = prior.copy()


KeyError: 0.5

In [12]:
# Define likelihood for chocolate cookies
likelihood_chocolate = {
    'Bowl 1': 0.5,   # Likelihood of chocolate from Bowl 1
    'Bowl 2': 0.25   # Likelihood of chocolate from Bowl 2
}

# Update posterior1 to get posterior2 based on the likelihood of chocolate
for hypo in posterior1:
    posterior1[hypo] *= likelihood_chocolate[hypo]

# Normalize the posterior
posterior1.normalize()

# Posterior after two observations (vanilla and chocolate)
posterior2 = posterior1.copy()


NameError: name 'posterior1' is not defined

In [13]:
# Define a new likelihood for the third observation (if applicable)
likelihood_third_observation = {
    'Bowl 1': 0.6,  # Replace with actual likelihood for the third observation
    'Bowl 2': 0.4
}

# Update posterior2 to get posterior3 based on the third observation
for hypo in posterior2:
    posterior2[hypo] *= likelihood_third_observation[hypo]

# Normalize the posterior
posterior2.normalize()

# Posterior after three observations
posterior3 = posterior2.copy()


NameError: name 'posterior2' is not defined

In [14]:
from empiricaldist import Pmf

# Define the prior distribution for two bowls
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])

# Define the likelihood for vanilla cookies
likelihood_vanilla = {
    'Bowl 1': 0.75,  # Likelihood of vanilla from Bowl 1
    'Bowl 2': 0.5    # Likelihood of vanilla from Bowl 2
}

# Update the prior based on the likelihood of observing one vanilla cookie
for hypo in prior:
    prior[hypo] *= likelihood_vanilla[hypo]

# Normalize the posterior to ensure it sums to 1
prior.normalize()

# Posterior after one vanilla cookie
posterior1 = prior.copy()  # Now `posterior1` is defined


KeyError: 0.5

In [15]:
# Define the likelihood for chocolate cookies
likelihood_chocolate = {
    'Bowl 1': 0.5,   # Likelihood of chocolate from Bowl 1
    'Bowl 2': 0.25   # Likelihood of chocolate from Bowl 2
}

# Update `posterior1` based on the likelihood of observing a chocolate cookie
for hypo in posterior1:
    posterior1[hypo] *= likelihood_chocolate[hypo]

# Normalize the posterior
posterior1.normalize()

# Posterior after two observations (one vanilla, one chocolate)
posterior2 = posterior1.copy()
print(posterior2)


NameError: name 'posterior1' is not defined

In [17]:
import numpy as np

# Define `hypos` as an array or sequence representing your hypotheses
hypos = np.array([50, 100])  # Example: percentages or other numeric hypotheses


In [20]:
hypos = [6, 8, 12]

In [21]:
prior = Pmf(1/3, hypos)
prior

6     0.333333
8     0.333333
12    0.333333
dtype: float64

In [22]:
prior.qs

array([ 6,  8, 12], dtype=int64)

In [23]:
likelihood1 = 1/6, 1/8, 1/12

In [24]:
posterior = prior * likelihood1
posterior.normalize()
posterior

6     0.444444
8     0.333333
12    0.222222
dtype: float64

In [25]:
likelihood2 = 0, 1/8, 1/12

In [26]:
posterior *= likelihood2
posterior.normalize()
posterior

6     0.000000
8     0.692308
12    0.307692
dtype: float64

In [27]:
def update_dice(pmf, data):
    """Update pmf based on new data."""
    hypos = pmf.qs
    likelihood = 1 / hypos
    impossible = (data > hypos)
    likelihood[impossible] = 0
    pmf *= likelihood
    pmf.normalize()

In [28]:
pmf = prior.copy()
pmf

6     0.333333
8     0.333333
12    0.333333
dtype: float64

In [29]:
update_dice(pmf, 1)
update_dice(pmf, 7)
pmf

6     0.000000
8     0.692308
12    0.307692
dtype: float64

In [30]:
# Solution

pmf = prior.copy()
for data in [1, 3, 5, 7]:
    update_dice(pmf, data)
    
pmf

6     0.000000
8     0.835052
12    0.164948
dtype: float64

In [31]:
# Solution

# Notice that I don't bother to normalize the prior.
# The `Pmf` gets normalized during the update, so we
# don't have to normalize it before.

ps = [1,2,3,4,5]
qs = [4,6,8,12,20]
pmf = Pmf(ps, qs)
update_dice(pmf, 7)
pmf

4     0.000000
6     0.000000
8     0.391304
12    0.347826
20    0.260870
dtype: float64

In [32]:
# Solution

# In the BlackWhite drawer, the probability of getting a match is 1/2
# In the RedGreenBlue drawer, the probability of a match is 1/3

hypos = ['BlackWhite', 'RedGreenBlue']
prior = Pmf(1/2, hypos)
likelihood = 1/2, 1/3
posterior = prior * likelihood
posterior.normalize()
posterior

BlackWhite      0.6
RedGreenBlue    0.4
dtype: float64

In [33]:
# Solution

# If I drew from the BlackWhite drawer, the probability the
# socks are white is 1/2

posterior['BlackWhite'] / 2

0.30000000000000004

In [34]:
# Solution

# The trick to this question is to notice that Elvis's twin was a brother.
# If they were identical twins, it is certain they would be the same sex.
# If they were fraternal twins, the likelihood is only 50%.

# Here's a solution using a Bayes table

import pandas as pd

table = pd.DataFrame(index=['identical', 'fraternal'])
table['prior'] = 1/3, 2/3
table['likelihood'] = 1, 1/2

table['unnorm'] = table['prior'] * table['likelihood']
prob_data = table['unnorm'].sum()

table['posterior'] = table['unnorm'] / prob_data
table

prior  likelihood    unnorm  posterior
identical  0.333333         1.0  0.333333        0.5
fraternal  0.666667         0.5  0.333333        0.5

In [35]:
# Solution

# Here's a solution using a Pmf

hypos = ['identical', 'fraternal']
prior = Pmf([1/3, 2/3], hypos)
prior

identical    0.333333
fraternal    0.666667
dtype: float64

In [36]:
# Solution

likelihood = 1, 1/2
posterior = prior * likelihood
posterior.normalize()
posterior

identical    0.5
fraternal    0.5
dtype: float64